#!/bin/bash

# ===================================================================================
# Environment variables used in this shell scripts (exported by caller script)
#
# CAP_ROOT                               : Location of the CAP directory/folder
# CAP_SRC="$CAP_ROOT/src/"               : Source code top folder
# CAP_BIN="$CAP_ROOT/bin/"               : Binary code folder (as produced by make install)
# CAP_LIB="$CAP_ROOT/lib/"               : CAP Libraries folder (as produced by make install)
# CAP_PROJECTS="$CAP_ROOT/projects/"     : Location of job configurations files (usually subfolders)
# CAP_DATA="$CAP_SRC/data/"              : Location of data used to run code e.g., PDG table
# CAP_MACROS="$CAP_SRC/Macros/"          : Location of main macros
# CAP_Clusters="$CAP_ROOT/Clusters/"     : Location of shell scripts (in subfolders)
# CAP_WSUGrid="$CAP_Clusters/WSUGrid/"   : Location of slurm shell scripts for Wayne State GRID
# CAP_INPUT_PATH="$CAP_DATA/InputFiles/" : Location of large data files (not managed by Git)
# CAP_OUTPUT_PATH="$CAP_WSUGrid"         : Location of Wayne State GrID outputs
# CAP_OUTPUT_SUBPATH=$1                  : Subfolder Location of outputs
# CAP_PRODUCTION=OUT`date +%Y%m%d%H%M`   : Autogenerated subfolder name for THIS production
# CAP_JOB_CONFIGURATION=$2               : Name of the configuration file provided on input (by user)
#
# Note 1: The macros and configuration files used by script are copied in the production directory
# Note 2: This scripts assumes root is provided within the conda environment CAP_CONDA.

conda init bash
conda activate CAP_CONDA
echo Using CONDA environment $CAP_CONDA
echo The root version is:
echo `which root` 
module load  pythia
TASKIX=$SLURM_ARRAY_TASK_ID
SEED=$(( SLURM_ARRAY_TASK_ID + SLURM_ARRAY_JOB_ID*100 ))
CAP_HISTOPATH=$CAP_WORKINGDIRECTORY_Output/$(printf "%02d/" $TASKIX )
echo "========================================================================================"
echo SLURM_ARRAY_TASK_ID is  $SLURM_ARRAY_TASK_ID
echo SLURM_ARRAY_JOB_ID is  $SLURM_ARRAY_JOB_ID
echo TASKIX is  $TASKIX
echo SEED is $SEED
echo NEVENTS is $CAP_NEVENTS
echo Will save histograms at $CAP_HISTOPATH
mkdir $CAP_HISTOPATH
echo "Calling root w/ RunAna"
echo "========================================================================================"
root -b "$CAP_MACROS/RunAna.C("\"$CAP_PROJECTS/$CAP_JOB_CONFIGURATION\"","\"$CAP_HISTOPATH\"",$SEED,true,$CAP_NEVENTS,1,1)"

