#!/bin/bash
if [ $# -gt 5 ]; then
  echo "usage: OUTPUT_SUBPATH  JOB_CONFIGURATION NMAINJOBS NSUBJOBS NEVENTS"
  exit 0
fi

if [ $# -lt 5 ]; then
  echo "usage: OUTPUT_SUBPATH  JOB_CONFIGURATION NMAINJOBS NSUBJOBS NEVENTS"
  exit 0
fi
echo Arg1: $1
echo Arg2: $2
echo Arg3: $3
echo Arg4: $4
echo Arg5: $5

if [ $3 -gt 40 ]; then
  echo "WARNING: Do you really want to launch more than 40 bunches?   "
  exit 0
fi
if [ $4 -gt 100 ]; then
  echo "WARNING: Do you really want to launch more than 100 sub-bunches...? "
  exit 0
fi


# =============================================================================================================
# Environment variables used in this and subsiduary shell scripts
#
# CAP_ROOT                               : Location of the CAP directory/folder
# CAP_SRC                                : Source code top folder
# CAP_BIN                                : Binary code folder (as produced by make install)
# CAP_LIB                                : Libraries folder (as produced by make install)
# CAP_CONFIG                             : Location of job configurations ini files
# CAP_GRID                               : Location of grid scripts
# CAP_GRID_WSU                           : Location of grid scripts for WSU slurm grid
# CAP_MACROS="$CAP_SRC/Macros/"          : Location of main macros
# CAP_INPUT_PATH="$CAP_DATA/InputFiles/" : Location of large data files (not managed by Git)
# CAP_OUTPUT_PATH="$CAP_WSUGrid"         : Location of Wayne State GrID outputs
# CAP_OUTPUT_SUBPATH=$1                  : Subfolder Location of outputs
# CAP_PRODUCTION=OUT`date +%Y%m%d%H%M`   : Autogenerated subfolder name for THIS production
# CAP_JOB_CONFIGURATION=$2               : Name of the configuration file provided on input (by user)
#
# Note 1: The macros and configuration files used by script are copied in the production directory
# Note 2: This and subsiduary scripts assumes root is provided within the conda environment CAP_CONDA.
#
# =============================================================================================================

export CAP_CONDA="CProot"
export CAP_ROOT="/home/cpruneau/CAP5.0/"
export CAP_SRC="$CAP_ROOT/src/"
export CAP_BIN="$CAP_ROOT/bin/"
export CAP_LIB="$CAP_ROOT/lib/"
export CAP_PROJECTS="$CAP_ROOT/projects/"
export CAP_MACROS="$CAP_SRC/Macros/"
export CAP_DATABASE="$CAP_ROOT/DB/"
export CAP_GRID="$CAP_ROOT/Grid/"
export CAP_GRID_WSU="$CAP_ROOT/Grid/WSU/"
export CAP_INPUT_PATH="$CAP_DATA/InputFiles/"
export PATH="$CAP_BIN:$PATH"
export DYLD_LIBRARY_PATH="$CAP_LIB:$DYLD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$CAP_LIB:$LD_LIBRARY_PATH"
export CAP_OUTPUT_PATH="$CAP_GRID_WSU"
export CAP_OUTPUT_SUBPATH=$1
export CAP_JOB_CONFIGURATION=$2
NMAINJOBS=$3
NSUBJOBS=$4
export CAP_NEVENTS=$5
CAP_PRODUCTION=OUT`date +%Y%m%d%H%M`
echo "Environment variables are now defined for CAP"

if [ -d $CAP_OUTPUT_PATH/$CAP_OUTPUT_SUBPATH/$CAP_PRODUCTION   ]
then
  echo Production directory $PRODUCTIONDIRECTORY does exist. WAIT AT LEAST ONE MINUTE!!!!
  exit 0
fi

if [ ! -e $CAP_PROJECTS/$CAP_JOB_CONFIGURATION   ]
then
  echo The configuration file $CAP_PROJECTS/$CAP_JOB_CONFIGURATION does not exist!!!!!
  exit 0
fi


mkdir $CAP_OUTPUT_PATH/$CAP_OUTPUT_SUBPATH/$CAP_PRODUCTION
echo Production $CAP_OUTPUT_PATH/$CAP_OUTPUT_SUBPATH/$CAP_PRODUCTION

# let's preserve the configuration
cp $CAP_MACROS/RunAna.C $CAP_OUTPUT_PATH/$CAP_OUTPUT_SUBPATH/$CAP_PRODUCTION
cp $CAP_MACROS/RunSum.C $CAP_OUTPUT_PATH/$CAP_OUTPUT_SUBPATH/$CAP_PRODUCTION
cp $CAP_MACROS/RunDerived.C $CAP_OUTPUT_PATH/$CAP_OUTPUT_SUBPATH/$CAP_PRODUCTION
cp $CAP_MACROS/RunSumDerived.C $CAP_OUTPUT_PATH/$CAP_OUTPUT_SUBPATH/$CAP_PRODUCTION
cp $CAP_MACROS/RunSumBalFct.C $CAP_OUTPUT_PATH/$CAP_OUTPUT_SUBPATH/$CAP_PRODUCTION
cp $CAP_PROJECTS/$CAP_JOB_CONFIGURATION  $CAP_OUTPUT_PATH/$CAP_OUTPUT_SUBPATH/$CAP_PRODUCTION

for ijob in $(seq 1 $NMAINJOBS)
do
  # launching the main generation jobs
  export CAP_WORKINGDIRECTORY=$CAP_OUTPUT_PATH/$CAP_OUTPUT_SUBPATH/$CAP_PRODUCTION/$(printf "BUNCH%02d" $ijob)
  export CAP_WORKINGDIRECTORY_Output=$CAP_WORKINGDIRECTORY
  echo Preparing to launch job  $ijob w/  working directory $CAP_WORKINGDIRECTORY w/ output $CAP_WORKINGDIRECTORY_Output
  mkdir -p $CAP_WORKINGDIRECTORY_Output
  sbatch -J batch__CAP -q primary --array=1-$NSUBJOBS --chdir=$CAP_WORKINGDIRECTORY --time=05:00:00 --mem=2G -o $CAP_WORKINGDIRECTORY/Job_%A_%a.out -e $CAP_WORKINGDIRECTORY/Job_%A_%a.err $CAP_GRID_WSU/RunAna.sh
  sleep 2s
done
